kind: pipeline
type: docker
name: default

steps:
- name: installation
  image: python
  commands:
  - pip install Flask
  - pip install requests

- name: checkos 
  image: python
  commands:
  - python ./checkos.py  

- name: hellodasha
  image: python
  commands:
  - python ./hello.py
 
- name: checkyear
  image: python
  commands:
  - python ./checkyear.py
